"""create table Message

Revision ID: 0085824f4c35
Revises: 
Create Date: 2021-09-21 20:02:45.745632

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0085824f4c35"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    # ### end Alembic commands ###
